// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon exige verify-full para evitar warning do pg v8→v9
    url: process.env["DATABASE_URL"]?.replace("sslmode=require", "sslmode=verify-full"),
  },
});
